[2024-05-03T13:47:53.171] [ERROR] app - Error: asdasd
    at get (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/applications/controller.js:5:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-05-03T15:30:04.767] [ERROR] app - Error: Invalid model given 
    at createApplication (file:///E:/Projects/Git/AISearch/back-end/src/repositories/applications/applications-repository.js:30:15)
    at createApplication (file:///E:/Projects/Git/AISearch/back-end/src/lib/applications/applications-service.js:43:36)
    at create (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/applications/controller.js:12:24)
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/validation/body-validation.js:7:9
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
[2024-05-03T15:32:16.092] [ERROR] app - error: insert into "applications" ("description", "imageId", "name", "subtitle", "url") values ($1, DEFAULT, $2, $3, $4) returning * - стовпець "imageId" зв'язку "applications" не існує
    at Parser.parseErrorMessage (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:283:98)
    at Parser.handlePacket (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:122:29)
    at Parser.parse (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:35:38)
    at Socket.<anonymous> (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 154,
  severity: 'ПОМИЛКА',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '44',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1057',
  routine: 'checkInsertTargets'
}
[2024-05-03T15:43:42.196] [ERROR] app - error: insert into "applications" ("description", "imageId", "name", "subtitle", "url") values ($1, DEFAULT, $2, $3, $4) returning * - стовпець "imageId" зв'язку "applications" не існує
    at Parser.parseErrorMessage (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:283:98)
    at Parser.handlePacket (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:122:29)
    at Parser.parse (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:35:38)
    at Socket.<anonymous> (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 154,
  severity: 'ПОМИЛКА',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '44',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1057',
  routine: 'checkInsertTargets'
}
[2024-05-03T15:46:04.966] [ERROR] app - TypeError: Cannot read properties of undefined (reading 'mimetype')
    at isImage (file:///E:/Projects/Git/AISearch/back-end/src/lib/common/files.js:24:41)
    at createImage (file:///E:/Projects/Git/AISearch/back-end/src/lib/images/index.js:5:10)
    at createApplication (file:///E:/Projects/Git/AISearch/back-end/src/lib/applications/applications-service.js:42:43)
    at create (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/applications/controller.js:9:24)
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/validation/body-validation.js:7:9
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
[2024-05-03T15:46:20.977] [ERROR] app - TypeError: Cannot read properties of undefined (reading 'mimetype')
    at isImage (file:///E:/Projects/Git/AISearch/back-end/src/lib/common/files.js:24:41)
    at createImage (file:///E:/Projects/Git/AISearch/back-end/src/lib/images/index.js:5:10)
    at createApplication (file:///E:/Projects/Git/AISearch/back-end/src/lib/applications/applications-service.js:42:43)
    at create (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/applications/controller.js:10:24)
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/validation/body-validation.js:7:9
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
[2024-05-03T16:30:30.131] [ERROR] app - Error: Invalid model given 
    at createApplication (file:///E:/Projects/Git/AISearch/back-end/src/repositories/applications/applications-repository.js:30:15)
    at createApplication (file:///E:/Projects/Git/AISearch/back-end/src/lib/applications/applications-service.js:43:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async create (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/applications/controller.js:9:18)
[2024-05-03T17:07:17.741] [ERROR] app - TypeError: res.binary is not a function
    at getByName (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/images/controller.js:5:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-05-03T17:13:36.518] [ERROR] app - TypeError: res.binary is not a function
    at getByName (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/images/controller.js:5:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-05-03T23:30:17.371] [ERROR] app - Error: data and salt arguments required
    at hashSync (E:\Projects\Git\AISearch\back-end\node_modules\bcrypt\bcrypt.js:91:15)
    at register (file:///E:/Projects/Git/AISearch/back-end/src/lib/auth/auth-service.js:14:26)
    at register (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/auth/auth-controller.js:4:24)
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/validation/body-validation.js:7:9
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
[2024-05-03T23:34:46.980] [ERROR] app - Error: Invalid salt. Salt must be in the form of: $Vers$log2(NumRounds)$saltvalue
    at hashSync (E:\Projects\Git\AISearch\back-end\node_modules\bcrypt\bcrypt.js:102:21)
    at register (file:///E:/Projects/Git/AISearch/back-end/src/lib/auth/auth-service.js:16:26)
    at register (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/auth/auth-controller.js:4:24)
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/validation/body-validation.js:7:9
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
[2024-05-03T23:41:45.422] [ERROR] app - Error: Cannot chain .first() on "insert" query
    at QueryBuilder_PostgreSQL.first (E:\Projects\Git\AISearch\back-end\node_modules\knex\lib\query\querybuilder.js:1146:13)
    at createUserRole (file:///E:/Projects/Git/AISearch/back-end/src/repositories/users/users-repository.js:31:54)
    at createDefaultUserRoles (file:///E:/Projects/Git/AISearch/back-end/src/lib/auth/permissions-service.js:10:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async register (file:///E:/Projects/Git/AISearch/back-end/src/lib/auth/auth-service.js:20:23)
    at async register (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/auth/auth-controller.js:4:18)
[2024-05-03T23:42:46.638] [ERROR] app - Error: Cannot chain .first() on "insert" query
    at QueryBuilder_PostgreSQL.first (E:\Projects\Git\AISearch\back-end\node_modules\knex\lib\query\querybuilder.js:1146:13)
    at createUserRole (file:///E:/Projects/Git/AISearch/back-end/src/repositories/users/users-repository.js:31:66)
    at createDefaultUserRoles (file:///E:/Projects/Git/AISearch/back-end/src/lib/auth/permissions-service.js:10:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async register (file:///E:/Projects/Git/AISearch/back-end/src/lib/auth/auth-service.js:20:23)
    at async register (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/auth/auth-controller.js:4:18)
[2024-05-03T23:44:53.105] [ERROR] app - TypeError: db is not iterable (cannot read property Symbol(Symbol.iterator))
    at createUserRole (file:///E:/Projects/Git/AISearch/back-end/src/repositories/users/users-repository.js:31:31)
    at createDefaultUserRoles (file:///E:/Projects/Git/AISearch/back-end/src/lib/auth/permissions-service.js:10:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async register (file:///E:/Projects/Git/AISearch/back-end/src/lib/auth/auth-service.js:20:23)
    at async register (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/auth/auth-controller.js:4:18)
[2024-05-11T18:42:27.066] [ERROR] app - error: insert into "users" ("email", "isAdmin", "nickname", "passwordHash") values ($1, $2, $3, $4) returning * - стовпець "isAdmin" зв'язку "users" не існує
    at Parser.parseErrorMessage (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:283:98)
    at Parser.handlePacket (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:122:29)
    at Parser.parse (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:35:38)
    at Socket.<anonymous> (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 147,
  severity: 'ПОМИЛКА',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '31',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1057',
  routine: 'checkInsertTargets'
}
[2024-05-11T18:44:33.760] [ERROR] app - Error: Undefined binding(s) detected when compiling FIRST. Undefined column(s): [email] query: select * from "users" where "email" = ? limit ?
    at QueryCompiler_PG.toSQL (E:\Projects\Git\AISearch\back-end\node_modules\knex\lib\query\querycompiler.js:112:13)
    at QueryBuilder_PostgreSQL.toSQL (E:\Projects\Git\AISearch\back-end\node_modules\knex\lib\query\querybuilder.js:84:44)
    at ensureConnectionCallback (E:\Projects\Git\AISearch\back-end\node_modules\knex\lib\execution\internal\ensure-connection-callback.js:4:30)
    at Runner.ensureConnection (E:\Projects\Git\AISearch\back-end\node_modules\knex\lib\execution\runner.js:318:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Runner.run (E:\Projects\Git\AISearch\back-end\node_modules\knex\lib\execution\runner.js:30:19)
    at async authenticate (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/auth/auth-controller.js:28:18)
[2024-05-11T18:45:30.678] [ERROR] app - Error: Undefined binding(s) detected when compiling FIRST. Undefined column(s): [email] query: select * from "users" where "email" = ? limit ?
    at QueryCompiler_PG.toSQL (E:\Projects\Git\AISearch\back-end\node_modules\knex\lib\query\querycompiler.js:112:13)
    at QueryBuilder_PostgreSQL.toSQL (E:\Projects\Git\AISearch\back-end\node_modules\knex\lib\query\querybuilder.js:84:44)
    at ensureConnectionCallback (E:\Projects\Git\AISearch\back-end\node_modules\knex\lib\execution\internal\ensure-connection-callback.js:4:30)
    at Runner.ensureConnection (E:\Projects\Git\AISearch\back-end\node_modules\knex\lib\execution\runner.js:318:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Runner.run (E:\Projects\Git\AISearch\back-end\node_modules\knex\lib\execution\runner.js:30:19)
    at async authenticate (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/auth/auth-controller.js:28:18)
[2024-05-11T18:46:08.840] [ERROR] app - Error: data and hash arguments required
    at Object.compare (E:\Projects\Git\AISearch\back-end\node_modules\bcrypt\bcrypt.js:208:17)
    at E:\Projects\Git\AISearch\back-end\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at module.exports.promise (E:\Projects\Git\AISearch\back-end\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (E:\Projects\Git\AISearch\back-end\node_modules\bcrypt\bcrypt.js:204:25)
    at authenticate (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/auth/auth-controller.js:33:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-05-11T22:06:01.531] [ERROR] app - error: select * where "email" = $1 limit $2 - SELECT * повинен посилатись на таблиці
    at Parser.parseErrorMessage (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:283:98)
    at Parser.handlePacket (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:122:29)
    at Parser.parse (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:35:38)
    at Socket.<anonymous> (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 143,
  severity: 'ПОМИЛКА',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '8',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1315',
  routine: 'ExpandAllTables'
}
[2024-05-11T22:14:44.499] [ERROR] app - TypeError: req.params.has is not a function
    at saveToLibrary (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/applications/controller.js:19:21)
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/validation/url-params-validation.js:7:9
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/auth/index.js:12:9
    at E:\Projects\Git\AISearch\back-end\node_modules\jsonwebtoken\verify.js:261:12
[2024-05-11T22:15:31.032] [ERROR] app - Error: Invalid model given 
    at createUserSave (file:///E:/Projects/Git/AISearch/back-end/src/repositories/userSaves/user-saves-repository.js:8:15)
    at saveToLibrary (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/applications/controller.js:29:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-05-11T22:16:17.127] [ERROR] app - Error: Cannot chain .first() on "insert" query
    at QueryBuilder_PostgreSQL.first (E:\Projects\Git\AISearch\back-end\node_modules\knex\lib\query\querybuilder.js:1146:13)
    at createUserSave (file:///E:/Projects/Git/AISearch/back-end/src/repositories/userSaves/user-saves-repository.js:11:80)
    at saveToLibrary (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/applications/controller.js:29:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-05-11T22:23:19.424] [ERROR] app - error: insert into "userSaves" ("applicationId", "savedBy") values ($1, $2) returning * - стовпець "savedBy" зв'язку "userSaves" не існує
    at Parser.parseErrorMessage (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:283:98)
    at Parser.handlePacket (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:122:29)
    at Parser.parse (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:35:38)
    at Socket.<anonymous> (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 151,
  severity: 'ПОМИЛКА',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '43',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1057',
  routine: 'checkInsertTargets'
}
[2024-05-11T22:52:02.714] [ERROR] app - ReferenceError: creationModel is not defined
    at findUserSaves (file:///E:/Projects/Git/AISearch/back-end/src/repositories/userSaves/user-saves-repository.js:16:53)
    at getLibrary (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/applications/controller.js:33:24)
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/auth/index.js:12:9
    at E:\Projects\Git\AISearch\back-end\node_modules\jsonwebtoken\verify.js:261:12
    at getSecret (E:\Projects\Git\AISearch\back-end\node_modules\jsonwebtoken\verify.js:97:14)
    at module.exports [as verify] (E:\Projects\Git\AISearch\back-end\node_modules\jsonwebtoken\verify.js:101:10)
    at authenticateToken (file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/auth/index.js:9:9)
[2024-05-11T22:52:45.483] [ERROR] app - error: select * from "userSaves" inner join "userSaves" on "applications"."id" = "userSaves"."applicationId" where "savedBy" = $1 - ім'я таблиці "userSaves" вказано більше одного разу
    at Parser.parseErrorMessage (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:283:98)
    at Parser.handlePacket (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:122:29)
    at Parser.parse (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:35:38)
    at Socket.<anonymous> (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 169,
  severity: 'ПОМИЛКА',
  code: '42712',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '466',
  routine: 'checkNameSpaceConflicts'
}
[2024-05-11T22:57:21.929] [ERROR] app - error: select "userSaves" as "saves", "applications" as "applicationsAlias" from "userSaves" inner join "saves" on "applicationsAlias"."id" = "saves"."applicationId" where "savedBy" = $1 - відношення "saves" не існує
    at Parser.parseErrorMessage (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:283:98)
    at Parser.handlePacket (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:122:29)
    at Parser.parse (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:35:38)
    at Socket.<anonymous> (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 126,
  severity: 'ПОМИЛКА',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '98',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1452',
  routine: 'parserOpenTable'
}
[2024-05-11T22:59:04.492] [ERROR] app - error: select "applications" from "userSaves" inner join "userSaves" on "applications"."id" = "userSaves"."applicationId" where "savedBy" = $1 - ім'я таблиці "userSaves" вказано більше одного разу
    at Parser.parseErrorMessage (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:283:98)
    at Parser.handlePacket (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:122:29)
    at Parser.parse (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:35:38)
    at Socket.<anonymous> (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 169,
  severity: 'ПОМИЛКА',
  code: '42712',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '466',
  routine: 'checkNameSpaceConflicts'
}
[2024-05-11T23:02:14.892] [ERROR] app - error: select "applications"."" from "userSaves" inner join "applications" on "applications"."id" = "userSaves"."applicationId" where "savedBy" = $1 - пустий ідентифікатор із роздільниками в або поблизу """"
    at Parser.parseErrorMessage (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:283:98)
    at Parser.handlePacket (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:122:29)
    at Parser.parse (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:35:38)
    at Socket.<anonymous> (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 173,
  severity: 'ПОМИЛКА',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '23',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1245',
  routine: 'scanner_yyerror'
}
[2024-05-13T21:53:08.982] [ERROR] app - Error: Invalid model given
    at createItem (file:///E:/Projects/Git/AISearch/back-end/src/repositories/common.js:22:15)
    at createApplicationRate (file:///E:/Projects/Git/AISearch/back-end/src/repositories/applicationRates/application-rates-repository.js:6:12)
    at rateApplication (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/applications/controller.js:44:11)
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/validation/body-validation.js:7:9
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
[2024-05-13T21:53:53.299] [ERROR] app - Error: Invalid model given
    at createItem (file:///E:/Projects/Git/AISearch/back-end/src/repositories/common.js:22:15)
    at createApplicationRate (file:///E:/Projects/Git/AISearch/back-end/src/repositories/applicationRates/application-rates-repository.js:6:12)
    at rateApplication (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/applications/controller.js:44:11)
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/validation/body-validation.js:7:9
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
[2024-05-13T21:54:44.231] [ERROR] app - Error: Invalid model given
    at createItem (file:///E:/Projects/Git/AISearch/back-end/src/repositories/common.js:22:15)
    at createApplicationRate (file:///E:/Projects/Git/AISearch/back-end/src/repositories/applicationRates/application-rates-repository.js:6:12)
    at rateApplication (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/applications/controller.js:44:11)
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/validation/body-validation.js:7:9
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
[2024-05-13T21:54:56.233] [ERROR] app - Error: ValidationError: "rating" is required
    at createItem (file:///E:/Projects/Git/AISearch/back-end/src/repositories/common.js:22:15)
    at createApplicationRate (file:///E:/Projects/Git/AISearch/back-end/src/repositories/applicationRates/application-rates-repository.js:6:12)
    at rateApplication (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/applications/controller.js:44:11)
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/validation/body-validation.js:7:9
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
[2024-05-13T21:56:10.299] [ERROR] app - error: update "applications" set "rating" = ($1 * ratedCount + $2) / (ratedCount + 1) where "id" = $3 - стовпця "ratedcount" не існує
    at Parser.parseErrorMessage (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:283:98)
    at Parser.handlePacket (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:122:29)
    at Parser.parse (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:35:38)
    at Socket.<anonymous> (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 240,
  severity: 'ПОМИЛКА',
  code: '42703',
  detail: undefined,
  hint: 'Можливо, передбачалось посилання на стовпець "applications.ratedCount".',
  position: '44',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3729',
  routine: 'errorMissingColumn'
}
[2024-05-13T22:07:20.190] [ERROR] app - error: update "applications" set "rating" = $1, "ratedCount" = $2 - неприпустимий синтаксис для типу integer: "3.6666666666666665"
    at Parser.parseErrorMessage (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:283:98)
    at Parser.handlePacket (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:122:29)
    at Parser.parse (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:35:38)
    at Socket.<anonymous> (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 227,
  severity: 'ПОМИЛКА',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: "параметр порталу без назви $1 = '...'",
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'numutils.c',
  line: '620',
  routine: 'pg_strtoint32_safe'
}
[2024-05-13T22:12:11.705] [ERROR] app - error: update "applications" set "rating" = $1, "ratedCount" = $2 - неприпустимий синтаксис для типу integer: "4.666666666666667"
    at Parser.parseErrorMessage (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:283:98)
    at Parser.handlePacket (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:122:29)
    at Parser.parse (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:35:38)
    at Socket.<anonymous> (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 226,
  severity: 'ПОМИЛКА',
  code: '22P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: "параметр порталу без назви $1 = '...'",
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'numutils.c',
  line: '620',
  routine: 'pg_strtoint32_safe'
}
[2024-05-13T23:32:04.698] [ERROR] app - TypeError: Cannot read properties of undefined (reading 'id')
    at updateProfile (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/auth/auth-controller.js:28:44)
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at file:///E:/Projects/Git/AISearch/back-end/src/api/middleware/validation/body-validation.js:7:9
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
    at Layer.handle [as handle_request] (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\router\route.js:119:3)
    at newFn (E:\Projects\Git\AISearch\back-end\node_modules\express-async-errors\index.js:16:20)
[2024-05-13T23:35:45.526] [ERROR] app - Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (node:_http_outgoing:652:11)
    at ServerResponse.header (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\response.js:795:10)
    at ServerResponse.send (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\response.js:175:12)
    at ServerResponse.json (E:\Projects\Git\AISearch\back-end\node_modules\express\lib\response.js:279:15)
    at register (file:///E:/Projects/Git/AISearch/back-end/src/api/controllers/auth/auth-controller.js:31:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
[2024-05-14T00:10:02.446] [ERROR] app - error: delete from "applications" where "id" = $1 - update або delete в таблиці "applications" порушує обмеження зовнішнього ключа "labels_applicationid_foreign" таблиці "labels"
    at Parser.parseErrorMessage (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:283:98)
    at Parser.handlePacket (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:122:29)
    at Parser.parse (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\parser.js:35:38)
    at Socket.<anonymous> (E:\Projects\Git\AISearch\back-end\node_modules\pg-protocol\dist\index.js:11:42)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 386,
  severity: 'ПОМИЛКА',
  code: '23503',
  detail: 'На ключ (id)=(3) все ще є посилання в таблиці "labels".',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'labels',
  column: undefined,
  dataType: undefined,
  constraint: 'labels_applicationid_foreign',
  file: 'ri_triggers.c',
  line: '2633',
  routine: 'ri_ReportViolation'
}
